language: rust
rust:
  - nightly

cache: cargo

script:
  - cargo clean && cargo build --verbose --no-default-features --features "notifier-twilio","notifier-slack"
  - cargo test --verbose --no-default-features --features "notifier-twilio","notifier-slack"